export const defaultState = {
  score: 0,
  time: "",
  hints: 5,
  answer: "",
  questions: [],
  fiftyFifty: 2,
  wrongCount: 0,
  gameOver: false,
  correctCount: 0,
  currentQuestion: {},
  numberOfQuestions: 0,
  currentQuestionIdx: 0,
  usedFiftyFifty: false,
  previousRandomNumbers: [],
  disableNextButton: false,
  disablePreviousButton: true,
  numberOfAnsweredQuestions: 0,
};
