export const defaultState = {
  score: 0,
  time: {},
  hints: 5,
  answer: " ",
  questions: [],
  fiftyFifty: 2,
  wrongAnswers: 0,
  nextQuestion: {},
  correctAnswers: 0,
  currentQuestion: {},
  previousQuestion: {},
  numberOfQuestions: 0,
  usedFiftyFifty: false,
  currentQuestionIndex: 0,
  previousRandomNumbers: [],
  disableNextButton: false,
  disablePreviousButton: true,
  numberOfAnsweredQuestions: 0,
};